config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	has_one :recommendation
	has_many :interviews
	has_one :firm, -> { where(recruiter: true)}, through: :recommendation
	has_many :firms, through: :interviews
end

app/models/firm.rb
class Firm < ApplicationRecord
	has_many :recommendations
	has_many :interviews
	has_many :candidates, through: :recommendations
	has_many :candidates, through: :interviews
end

app/models/interview.rb
class Interview < ApplicationRecord
 	belongs_to :firm
 	belongs_to :candidate
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
	belongs_to :firm
	belongs_to :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@jobs = SearchJobs.new(@firms).perform
  end


  def show
  	@jobs = SearchJobs.new(@firms).perform #démarrage du scraper

  	ex_json = File.read('public/temp.json') #je lis l'ancien json du scrap précédent
	@ex_hash = JSON.parse(ex_json) # je parse le fichier pour utiliser les anciennes données
	@used_in_mail = []

	File.open("public/temp.json","w") do |f|  # j'ouvre et stocke les nouvelles données
		 f.write(@jobs.to_json)
	end

	overlapping_elements = @jobs.to_a & @ex_hash.to_a
	@exc1 = @jobs.to_a - overlapping_elements #array modifié contenant un nouveau job
	@exc2 = @ex_hash.to_a - overlapping_elements

		if @exc1.count > 0 
		n=0
			@exc1.each do |key|
				@new_jobs = key[1]

			begin
				@ex_jobs = @exc2[n][1]
			rescue
			end
			@only_new_elements = @new_jobs.difference(@ex_jobs)
	 	n=n+1
		end
	else 
		end 
	UserMailer.new_job_mailer(@ex_hash).deliver_now!
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h1> Tous les jobs : </h1> <br><br>

<% @jobs.each do |firm, jobs| %>

<h2 style ="color: #5994E0">
	<b><%= firm.gsub("https://www.welcometothejungle.co/companies/","").gsub("/jobs","").capitalize %> :</b></h2>
	<br>

		<% jobs.each do |key| %>
			<li><%= key %></li>
		<% end %> <br><br>
<% end %>

<br><br><br>

<h1> Les nouveaux jobs par rapport au dernier scrapping : </h1> <br><br>

<% if @exc1.count > 0 %>

	<% n=0 %>
	<% @exc1.each do |key| %>

		<h2 style ="color: #5994E0"> Chez <%= key[0].gsub("https://www.welcometothejungle.co/companies/","").gsub("/jobs","").capitalize %> : </h2>

		<!-- key[1] est un array de NOUVEAUX jobs qui a été modifié. Boucler dessus ressort chaque job de l'array -->
		<!-- L'objectif est de comparer ce key[1] avec l'ancien key[1] (issu de ex_hash) afin de sortir la valeur étrangère -->

		<% @new_jobs = key[1] %> <br>

			<% key[1].each do |job| %>
				<li> <%= job %> </li> 
			<% end %>

		<% begin %>
			<% @ex_jobs = @exc2[n][1] %>
		<% rescue %>
		<% end %>

<!-- On veut comparer @ex_jobs et @new_jobs pour sortir les différences : -->
			<% @only_new_elements = @new_jobs.difference(@ex_jobs) %>

<br><h4><b>	Voici les nouveaux jobs depuis le dernier scraping :</b></h4>
			<% @only_new_elements.each do |job| %>
				<li> <%= job %> </li>
			<% end %>
 	<% n= n+1 %>
	<% end %> <br>

<% else %>
	Pas de nouveau job au sein du réseau.
<% end %>

app/views/home/show.html.erb
<%= link_to "Accéder à tous les jobs", home_index_path %>


Voici les nouveaux jobs par rapport au dernier scrapping : <br> <br>

<% if @exc1.count > 0 %>

	<% n=0 %>
	<% @exc1.each do |key| %>

		<h2 style ="color: #5994E0"> Chez <%= key[0].gsub("https://www.welcometothejungle.co/companies/","").gsub("/jobs","").capitalize %> : </h2>

		<!-- key[1] est un array de NOUVEAUX jobs qui a été modifié. Boucler dessus ressort chaque job de l'array -->
		<!-- L'objectif est de comparer ce key[1] avec l'ancien key[1] (issu de ex_hash) afin de sortir la valeur étrangère -->

		<% @new_jobs = key[1] %> <br>

			<% key[1].each do |job| %>
				<li> <%= job %> </li> 
			<% end %>

		<% begin %>
			<% @ex_jobs = @exc2[n][1] %>
		<% rescue %>
		<% end %>

<!-- On veut comparer @ex_jobs et @new_jobs pour sortir les différences : -->
			<% @only_new_elements = @new_jobs.difference(@ex_jobs) %>

<br><h4><b>	Voici les nouveaux jobs depuis le dernier scraping :</b></h4>
			<% @only_new_elements.each do |job| %>
				<li> <%= job %> </li>
			<% end %>
 	<% n= n+1 %>
	<% end %> <br>

<% else %>
	Pas de nouveau job au sein du réseau.
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>